"""create locations and aq_measurements

Revision ID: b3d1da28a543
Revises: 
Create Date: 2026-02-17 14:15:42.749548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d1da28a543'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('aq_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'timestamp_utc', 'parameter', 'source', name='uq_aq')
    )
    op.create_index('ix_aq_loc_time', 'aq_measurements', ['location_id', 'timestamp_utc'], unique=False)
    op.create_index(op.f('ix_aq_measurements_location_id'), 'aq_measurements', ['location_id'], unique=False)
    op.create_index(op.f('ix_aq_measurements_timestamp_utc'), 'aq_measurements', ['timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aq_measurements_timestamp_utc'), table_name='aq_measurements')
    op.drop_index(op.f('ix_aq_measurements_location_id'), table_name='aq_measurements')
    op.drop_index('ix_aq_loc_time', table_name='aq_measurements')
    op.drop_table('aq_measurements')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
