"""add subscriptions

Revision ID: d397ee215ea1
Revises: d91d2b6c4f3d
Create Date: 2026-02-22 19:12:30.020219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd397ee215ea1'
down_revision: Union[str, Sequence[str], None] = 'd91d2b6c4f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'location_id', name='uq_sub_email_location')
    )
    op.create_index(op.f('ix_subscriptions_email'), 'subscriptions', ['email'], unique=False)
    op.create_index(op.f('ix_subscriptions_location_id'), 'subscriptions', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_location_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_email'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
