"""add weather_hourly and daily_metrics

Revision ID: d91d2b6c4f3d
Revises: b3d1da28a543
Create Date: 2026-02-21 16:10:10.000389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91d2b6c4f3d'
down_revision: Union[str, Sequence[str], None] = 'b3d1da28a543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('pm25_avg', sa.Float(), nullable=True),
    sa.Column('pm25_max', sa.Float(), nullable=True),
    sa.Column('bad_hours', sa.Integer(), nullable=False),
    sa.Column('bad_day', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'day', name='uq_daily_loc_day')
    )
    op.create_index('ix_daily_loc_day', 'daily_metrics', ['location_id', 'day'], unique=False)
    op.create_index(op.f('ix_daily_metrics_day'), 'daily_metrics', ['day'], unique=False)
    op.create_index(op.f('ix_daily_metrics_location_id'), 'daily_metrics', ['location_id'], unique=False)
    op.create_table('weather_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('rh', sa.Float(), nullable=True),
    sa.Column('wind_kmh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'timestamp_utc', name='uq_weather_loc_time')
    )
    op.create_index(op.f('ix_weather_hourly_location_id'), 'weather_hourly', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_hourly_timestamp_utc'), 'weather_hourly', ['timestamp_utc'], unique=False)
    op.create_index('ix_weather_loc_time', 'weather_hourly', ['location_id', 'timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_loc_time', table_name='weather_hourly')
    op.drop_index(op.f('ix_weather_hourly_timestamp_utc'), table_name='weather_hourly')
    op.drop_index(op.f('ix_weather_hourly_location_id'), table_name='weather_hourly')
    op.drop_table('weather_hourly')
    op.drop_index(op.f('ix_daily_metrics_location_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_day'), table_name='daily_metrics')
    op.drop_index('ix_daily_loc_day', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
